/* Carga inicial de exemplo — baseada no modelo real de importação
   (Painel de Serviços) e no catálogo de tipos de serviço.
   Substitua importando sua planilha real (botão "Importar planilha").
   O "criadoEm" é a data/hora de abertura; o tempo em atendimento e o
   status de prazo são recalculados sozinhos, comparando com agora. */
const OPS_SEED_DATA = [
  {
    "protocolo": "8596631/1",
    "tituloCompleto": "OPERAÇÕES - SERVIÇOS ADICIONAIS",
    "tipoCurto": "SERVIÇOS ADICIONAIS",
    "slaHoras": 48.0,
    "catalogado": true,
    "cidade": "Acari",
    "bairro": "Dinarte Mariz",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T05:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8596364/1",
    "tituloCompleto": "OPERAÇÕES - TROCA DE ENDEREÇO",
    "tipoCurto": "TROCA DE ENDEREÇO",
    "slaHoras": 72.0,
    "catalogado": true,
    "cidade": "Canguaretama",
    "bairro": "Vila Vintém (rua de trás)",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T05:49:41.493771",
    "tempoManual": null,
    "prazoManual": null,
    "lat": -6.379,
    "lng": -35.131
  },
  {
    "protocolo": "8596206/1",
    "tituloCompleto": "OPERAÇÕES - CABO BAIXO",
    "tipoCurto": "CABO BAIXO",
    "slaHoras": 24.0,
    "catalogado": true,
    "cidade": "Carnaúba dos Dantas",
    "bairro": "Dom José Adelino Dantas",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T05:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8595934/1",
    "tituloCompleto": "OPERAÇÕES - SEM ACESSO",
    "tipoCurto": "SEM ACESSO",
    "slaHoras": 24.0,
    "catalogado": true,
    "cidade": "Carnaúba dos Dantas",
    "bairro": "Conjunto Seu Anísio",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T04:49:41.493771",
    "tempoManual": null,
    "prazoManual": null,
    "lat": -6.551,
    "lng": -36.649
  },
  {
    "protocolo": "8598265/1",
    "tituloCompleto": "OPERAÇÕES - DIFICULDADES DE ACESSO",
    "tipoCurto": "DIFICULDADE DE ACESSO",
    "slaHoras": 24.0,
    "catalogado": true,
    "cidade": "Ceará-Mirim",
    "bairro": "Planalto",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T09:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8595430/1",
    "tituloCompleto": "OPERAÇÕES - SEM ACESSO",
    "tipoCurto": "SEM ACESSO",
    "slaHoras": 24.0,
    "catalogado": true,
    "cidade": "Ceará-Mirim",
    "bairro": "Muriú",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T03:49:41.493771",
    "tempoManual": null,
    "prazoManual": null,
    "lat": -5.556,
    "lng": -35.365
  },
  {
    "protocolo": "8593117/1",
    "tituloCompleto": "OPERAÇÕES - FIBRA ATIVAÇÃO (INSTALAÇÃO)",
    "tipoCurto": "ATIVAÇÃO",
    "slaHoras": 72.0,
    "catalogado": true,
    "cidade": "Extremoz",
    "bairro": "Sport Club Natureza",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-14T12:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8557522/2",
    "tituloCompleto": "BOT - FIBRA ATIVAÇÃO",
    "tipoCurto": "ATIVAÇÃO",
    "slaHoras": 72.0,
    "catalogado": true,
    "cidade": "Jardim do Seridó",
    "bairro": "Bela Vista",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-09T05:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8596904/1",
    "tituloCompleto": "OPERAÇÕES - FIBRA ATIVAÇÃO (INSTALAÇÃO)",
    "tipoCurto": "ATIVAÇÃO",
    "slaHoras": 72.0,
    "catalogado": true,
    "cidade": "Natal",
    "bairro": "Felipe Camarão",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T06:49:41.493771",
    "tempoManual": null,
    "prazoManual": null,
    "lat": -5.812,
    "lng": -35.246
  },
  {
    "protocolo": "8597833/1",
    "tituloCompleto": "OPERAÇÕES - RECOLHIMENTO/TROCA DE ENDEREÇO",
    "tipoCurto": "RECOLHIMENTO",
    "slaHoras": 48.0,
    "catalogado": true,
    "cidade": "Parelhas",
    "bairro": "Ivan Bezerra",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T08:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8597815/1",
    "tituloCompleto": "OPERAÇÕES - TROCA DE ENDEREÇO",
    "tipoCurto": "TROCA DE ENDEREÇO",
    "slaHoras": 72.0,
    "catalogado": true,
    "cidade": "Parelhas",
    "bairro": "Ivan Bezerra",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T08:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8597042/1",
    "tituloCompleto": "OPERAÇÕES - RECOLHIMENTO/TROCA DE ENDEREÇO",
    "tipoCurto": "RECOLHIMENTO",
    "slaHoras": 48.0,
    "catalogado": true,
    "cidade": "Parelhas",
    "bairro": "Ivan Bezerra",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T06:49:41.493771",
    "tempoManual": null,
    "prazoManual": null,
    "lat": -6.676,
    "lng": -36.655
  },
  {
    "protocolo": "8595129/1",
    "tituloCompleto": "OPERAÇÕES - FIBRA ATIVAÇÃO (INSTALAÇÃO)",
    "tipoCurto": "ATIVAÇÃO",
    "slaHoras": 72.0,
    "catalogado": true,
    "cidade": "Parelhas",
    "bairro": "Maria Terceira",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T03:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8591338/3",
    "tituloCompleto": "OPERAÇÕES - FIBRA ATIVAÇÃO (INSTALAÇÃO)",
    "tipoCurto": "ATIVAÇÃO",
    "slaHoras": 72.0,
    "catalogado": true,
    "cidade": "Parelhas",
    "bairro": "Ivan Bezerra",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T09:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8584930/3",
    "tituloCompleto": "BOT - FIBRA ATIVAÇÃO",
    "tipoCurto": "ATIVAÇÃO",
    "slaHoras": 72.0,
    "catalogado": true,
    "cidade": "Parelhas",
    "bairro": "Ivan Bezerra",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T05:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8583762/4",
    "tituloCompleto": "OPERAÇÕES - RETENÇÃO CLIENTE CRÍTICO",
    "tipoCurto": "RETENÇÃO CLIENTE CRITICO",
    "slaHoras": 24.0,
    "catalogado": true,
    "cidade": "Parelhas",
    "bairro": "Centro",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-15T09:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8458046/1",
    "tituloCompleto": "OPERAÇÕES - RECOLHIMENTO/TROCA DE ENDEREÇO",
    "tipoCurto": "RECOLHIMENTO",
    "slaHoras": 48.0,
    "catalogado": true,
    "cidade": "Parelhas",
    "bairro": "Maria Terceira",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T06:49:41.493771",
    "tempoManual": null,
    "prazoManual": null
  },
  {
    "protocolo": "8596444/1",
    "tituloCompleto": "OPERAÇÕES - FIBRA ATIVAÇÃO (INSTALAÇÃO)",
    "tipoCurto": "ATIVAÇÃO",
    "slaHoras": 72.0,
    "catalogado": true,
    "cidade": "São José de Mipibu",
    "bairro": "Taborda",
    "telefone": "",
    "projeto": "OP-INST-VT-RN",
    "observacao": "",
    "criadoEm": "2026-07-16T05:49:41.493771",
    "tempoManual": null,
    "prazoManual": null,
    "lat": -6.065,
    "lng": -35.241
  }
];
